sonar.projectKey=juankuri_DSW01-Practica02
sonar.organization=juankuri-1
sonar.projectName=DSW01-Practica02
sonar.projectVersion=0.0.1
sonar.sourceEncoding=UTF-8

sonar.sources=src/main/java,frontend/src
sonar.tests=src/test/java,frontend/src
sonar.test.inclusions=**/*.spec.ts,**/*Test.java,**/*Tests.java,**/*TestCase.java
sonar.exclusions=**/node_modules/**,**/dist/**,**/target/**,**/cypress/**

sonar.java.binaries=target/classes
