name: 04 Docker Publish

on:
    push:
        branches: ["main", "dev"]
    workflow_dispatch:

jobs:
    docker:
        name: Build & Push to DockerHub
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@8e5e7e5ab8b370d6c329ec480dd894686673b4a1

            - name: Log in to DockerHub
              uses: docker/login-action@0d4c9c5ea7693da7b8450c2e9de73ca9cf534443
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@dd2bf708dd7b91d2d5bea92c47a5e1280055a906

            - name: Extract metadata - backend
              id: meta_backend
              uses: docker/metadata-action@507c2f2dc502c992ad446e3d7a5dfbe68a73a87e
              with:
                  images: ${{ secrets.DOCKER_USERNAME }}/empleados-backend
                  tags: |
                      type=ref,event=branch
                      type=sha,prefix=

            - name: Build & push backend image
              uses: docker/build-push-action@ca052428191007020496b6eca44d0eb17b11355c
              with:
                  context: .
                  file: ./Dockerfile
                  push: true
                  tags: ${{ steps.meta_backend.outputs.tags }}
                  labels: ${{ steps.meta_backend.outputs.labels }}
                  cache-from: type=gha
                  cache-to: type=gha,mode=max

            - name: Extract metadata - frontend
              id: meta_frontend
              uses: docker/metadata-action@507c2f2dc502c992ad446e3d7a5dfbe68a73a87e
              with:
                  images: ${{ secrets.DOCKER_USERNAME }}/empleados-frontend
                  tags: |
                      type=ref,event=branch
                      type=sha,prefix=

            - name: Build & push frontend image
              uses: docker/build-push-action@ca052428191007020496b6eca44d0eb17b11355c
              with:
                  context: ./frontend
                  file: ./frontend/Dockerfile
                  push: true
                  tags: ${{ steps.meta_frontend.outputs.tags }}
                  labels: ${{ steps.meta_frontend.outputs.labels }}
                  cache-from: type=gha
                  cache-to: type=gha,mode=max
